askmeanything/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns

import home.views

from home.views import AMAListView, AMADetailView, AMACreateView, UserFormView, SessionFormView, LogoutView

urlpatterns = [
    # AMA
    url(r'^$', AMAListView.as_view(), name='index'),
    url(r'^ama/create/$', AMACreateView.as_view(), name='createama'),
    url(r'^ama/(?P<pk>[0-9]+)/$', AMADetailView.as_view(), name='ama_detail'),
    url(r'^ama/(?P<ama_id>[0-9]+)/question/$', home.views.ask_question, name='question'),
    url(r'^ama/(?P<ama_id>[0-9]+)/question/(?P<question_id>[0-9]+)/$', home.views.question, name='question_detail'),

    # API
    url(r'^api/amas/', include("home.api.amas.urls", namespace='amas-api')),
    url(r'^api/comments/', include("home.api.comments.urls", namespace='comments-api')),
    url(r'^api/questions/', include("home.api.questions.urls", namespace='questions-api')),

    # Questions
    # url(r'questions/', home.views.QuestionList.as_view()),

    # Accounts
    url(r'^login/$', SessionFormView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^signup/$', UserFormView.as_view(), name='signup'),

    # Creation

    url(r'^admin/', admin.site.urls),
]

urlpatterns = format_suffix_patterns(urlpatterns)

home/api/amas/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from home.api.amas.views import (
    AMACreateAPIView,
    AMAListAPIView,
    AMADetailAPIView,
    AMADeleteAPIView,
    AMAUpdateAPIView,
    )

urlpatterns = [
    url(r'^$', AMAListAPIView.as_view(), name='list'),
    url(r'^create/$', AMACreateAPIView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', AMADetailAPIView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/delete/$', AMADeleteAPIView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/update/$', AMAUpdateAPIView.as_view(), name='update'),
]

home/api/comments/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from home.api.comments.views import (
    # CommentCreateAPIView,
    CommentListAPIView,
    CommentDetailAPIView,
    # CommentDeleteAPIView,
    # CommentUpdateAPIView,
    )

urlpatterns = [
    url(r'^$', CommentListAPIView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', CommentDetailAPIView.as_view(), name='detail'),
    # url(r'^amas/$', CommentListAPIView.as_view(), name='ama-list'),
    # url(r'^amas/create/$', CommentCreateAPIView.as_view(), name='ama-create'),
    # url(r'^amas/(?P<pk>\d+)/$', CommentDetailAPIView.as_view(), name='ama-detail'),
    # url(r'^amas/(?P<pk>\d+)/delete/$', CommentDeleteAPIView.as_view(), name='ama-delete'),
    # url(r'^amas/(?P<pk>\d+)/update/$', CommentUpdateAPIView.as_view(), name='ama-update'),
]

home/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from home.api.views import (
    AMACreateAPIView,
    AMAListAPIView,
    AMADetailAPIView,
    AMADeleteAPIView,
    AMAUpdateAPIView,
    )

urlpatterns = [
    url(r'^amas/$', AMAListAPIView.as_view(), name='ama-list'),
    url(r'^amas/create/$', AMACreateAPIView.as_view(), name='ama-create'),
    url(r'^amas/(?P<pk>\d+)/$', AMADetailAPIView.as_view(), name='ama-detail'),
    url(r'^amas/(?P<pk>\d+)/delete/$', AMADeleteAPIView.as_view(), name='ama-delete'),
    url(r'^amas/(?P<pk>\d+)/update/$', AMAUpdateAPIView.as_view(), name='ama-update'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import fields
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse, reverse_lazy


class AMA(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    pub_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('ama_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title[:20] + " " + str(self.id)

    def clean(self):
        if self.title == '':
            raise ValidationError('Title field can not be empty')

    def questions(self):
        return Question.objects.filter(ama=self)


class Comment(models.Model):
    author = models.ForeignKey(User)
    comment = models.CharField(max_length=400)
    pub_date = models.DateTimeField(default=timezone.now)

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    target = fields.GenericForeignKey('content_type', 'object_id')

    comments = fields.GenericRelation('self')

    def __str__(self):
        return self.author.username + "- " + self.comment[:20]


class Question(models.Model):
    author = models.ForeignKey(User, null=True)
    author_name = models.CharField(max_length=25, default='Anonymous')
    ama = models.ForeignKey(AMA, on_delete=models.CASCADE)
    question = models.CharField(max_length=400)
    pub_date = models.DateTimeField(default=timezone.now)
    comments = fields.GenericRelation(Comment)

    def __str__(self):
        return self.author_name + "- " + self.question[:20]

    def get_absolute_url(self):
        return reverse('ama_detail', kwargs={'pk': self.ama.id})


class Answer(models.Model):
    author = models.ForeignKey(User)
    question = models.OneToOneField(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=400)
    pub_date = models.DateTimeField(default=timezone.now)
    comments = fields.GenericRelation(Comment)

    def __str__(self):
        return self.author.username + "- " + self.answer[:20]

home/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import AMA, Question

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

class AMAForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = AMA
        fields = ['title', 'description']

class QuestionForm(forms.ModelForm):
    question = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Question
        fields = ['question', 'author_name']

home/api/amas/views.py
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveAPIView,
    DestroyAPIView,
    UpdateAPIView,
    RetrieveUpdateAPIView,
    )
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
    )

from home.models import AMA

from .permissions import IsOwnerOrReadOnly
from .serializers import (
    AMACreateUpdateSerializer,
    AMADetailSerializer,
    AMAListSerializer,
    )


class AMACreateAPIView(CreateAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMACreateUpdateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class AMADeleteAPIView(DestroyAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMADetailSerializer


class AMADetailAPIView(RetrieveAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMADetailSerializer


class AMAListAPIView(ListAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMAListSerializer


class AMAUpdateAPIView(RetrieveUpdateAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMACreateUpdateSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

home/api/comments/views.py
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveAPIView,
    DestroyAPIView,
    UpdateAPIView,
    RetrieveUpdateAPIView,
    )
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
    )

from home.models import Comment

from home.api.amas.permissions import IsOwnerOrReadOnly
from .serializers import (
    CommentListSerializer
    )


# class CommentCreateAPIView(CreateAPIView):
#     queryset = Comment.objects.all()
#     serializer_class = CommentCreateUpdateSerializer
#     permission_classes = [IsAuthenticated]
#
#     def perform_create(self, serializer):
#         serializer.save(author=self.request.user)


# class CommentDeleteAPIView(DestroyAPIView):
#     queryset = Comment.objects.all()
#     serializer_class = CommentDetailSerializer


class CommentDetailAPIView(RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentListSerializer


class CommentListAPIView(ListAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentListSerializer


# class CommentUpdateAPIView(RetrieveUpdateAPIView):
#     queryset = Comment.objects.all()
#     serializer_class = CommentCreateUpdateSerializer
#     permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

home/api/questions/views.py
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveAPIView,
    DestroyAPIView,
    UpdateAPIView,
    RetrieveUpdateAPIView,
    )
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
    )

from home.models import Question

from home.api.amas.permissions import IsOwnerOrReadOnly
from .serializers import (
    QuestionListSerializer
    )


# class QuestionCreateAPIView(CreateAPIView):
#     queryset = Question.objects.all()
#     serializer_class = QuestionCreateUpdateSerializer
#     permission_classes = [IsAuthenticated]
#
#     def perform_create(self, serializer):
#         serializer.save(author=self.request.user)


# class QuestionDeleteAPIView(DestroyAPIView):
#     queryset = Question.objects.all()
#     serializer_class = QuestionDetailSerializer


class QuestionDetailAPIView(RetrieveAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionListSerializer


class QuestionListAPIView(ListAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionListSerializer


# class QuestionUpdateAPIView(RetrieveUpdateAPIView):
#     queryset = Question.objects.all()
#     serializer_class = QuestionCreateUpdateSerializer
#     permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

home/api/views.py
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveAPIView,
    DestroyAPIView,
    UpdateAPIView,
    RetrieveUpdateAPIView,
    )
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
    )

from home.models import AMA

from .permissions import IsOwnerOrReadOnly
from .serializers import (
    AMACreateUpdateSerializer,
    AMADetailSerializer,
    AMASerializer,
    )


class AMACreateAPIView(CreateAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMACreateUpdateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

class AMADeleteAPIView(DestroyAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMADetailSerializer


class AMADetailAPIView(RetrieveAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMASerializer


class AMAListAPIView(ListAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMASerializer


class AMAUpdateAPIView(RetrieveUpdateAPIView):
    queryset = AMA.objects.all()
    serializer_class = AMACreateUpdateSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

home/templates/ama/create_ama.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <div class="col-xs-5 col-xs-offset-1">
    <h3>Submit an AMA</h3>
    <form class="" action="" method="POST">
      {% csrf_token %}
      {% include 'form_template.html' %}
      <!-- <div class="form-group">
        <label for="title">Title</label>
        <textarea name="title" class="form-control" rows="2" cols="40"></textarea>
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <textarea name="description" class="form-control" rows="8" cols="40"></textarea>
      </div> -->

      <input type="submit" value="Submit">
    </form>
  </div>
</div>

<br/>

<div class="row">
  <ul class="col-xs-5 col-xs-offset-1">
    {% for error in errors%}
    <li class="errors">{{ error }}</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

home/templates/ama/detail.html
{% extends "base.html" %}

{% block left-content %}
<a href="{% url 'index' %}">&#8592Back to index</a>

<h1>{{ ama.title }}</h1>
{% if ama.description %}
<p class="ama-description">
  {{ ama.description|linebreaksbr }}
</p>
{% endif %}

<h3 class="questions-header">Questions</h3>

<form class="speech-form" action="{{ request.path }}question/" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="question">Ask A Question</label>
    <textarea name="question" class="form-control question" rows="1" cols="1"></textarea>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-xs-2">
        <label>Ask as: </label>
      </div>
      <div class="col-xs-10">
        {% if user.username %}
        <label for="username">
          <input type="radio" name="author_name" id="username" value="{{ user.username }}" checked />
          {{ user.username }}
        </label>
        <label for="anonymous">
          <input type="radio" name="author_name" id="anonymous" value="other">
            Other: <input type="text" name="other" value='Anonymous' />
          </input>
        </label>
        {% else %}
        <input type="text" name="author_name">
        {% endif %}
      </div>
    </div>
  </div>

  <input type="submit" value="Submit">
</form>

<ul class="questions-list">
  {% for question in ama.question_set.all reversed %}
  <li class="question" id="question-{{ forloop.counter0 }}">
    <div class="question-author"><b>{{ question.author_name }}</b> {{ question.pub_date }}</div>
    <div class="question-text">{{ question.question|linebreaksbr }}</div>

    <div class="answer-box">
      {% if question.answer %}
      <p class="answer" id="answer-{{ forloop.counter0 }}">
        {{ question.answer.answer|linebreaksbr }}
      </p>
      {% else %}
      <p class="answer" id="answer-{{ forloop.counter0 }}" hidden>
      </p>
      {% endif %}

      {% if user.is_authenticated %}
        {% if question.ama.author == user %}
          {% if question.answer %}
          <a id="answer-button-{{ forloop.counter0 }}" href="{% url 'question_detail' ama.id question.id %}">Edit Answer</a>
          {% else %}
          <a id="answer-button-{{ forloop.counter0 }}" href="{% url 'question_detail' ama.id question.id %}">Answer</a>
          {% endif %}

          <script type="text/javascript">
            $(document).ready(function () {
              $('#answer-button-{{ forloop.counter0 }}').click(function (e) {
                e.preventDefault();
                e.target.hidden = true;
                var $answer = $('#answer-{{ forloop.counter0 }}')[0];
                $answer.hidden = true;

                var form = document.createElement('form');
                form.action = "{{ request.path }}question/{{ question.id }}/";
                form.method = "POST";

                var csrf_token = document.createElement('input');
                csrf_token.type = "hidden";
                csrf_token.name = "csrfmiddlewaretoken";
                csrf_token.value = csrftoken;

                var div = document.createElement('div');
                div.className = "form-group";

                var label = document.createElement('label');
                label.innerText = "Answer";

                var textarea = document.createElement('textarea');
                textarea.name = "response";
                textarea.innerText = "{{ question.answer.answer|addslashes|safe }}";

                var submit = document.createElement('input');
                submit.type = "submit";
                submit.value = "Save";

                div.appendChild(label);
                div.appendChild(textarea);
                form.appendChild(csrf_token);
                form.appendChild(div);
                form.appendChild(submit);
                $('#question-{{ forloop.counter0 }}').append(form);
              });
            });
          </script>
        {% else %}
        <a href="{% url 'question_detail' ama.id question.id %}">Comment</a>
        {% endif %}
      {% endif %}
    </div>

    <ul>
      {% for comment in question.comments.all %}
      <li>
        {% include "comment/detail.html" %}
      </li>
      {% endfor %}
    </ul>
  </li>
  {% endfor %}
</ul>

{% endblock %}

{% block right-content %}
<h5>
  <a href="{% url 'createama' %}" class="btn btn-primary btn-lg">
    SUBMIT AN AMA
  </a>
</h5>
{% endblock %}

home/templates/ama/index.html
{% extends "base.html" %}

{% block left-content %}
{% if ama_list %}
<ul class="ama-list">
  {% for ama in ama_list %}
  <li class="ama-list-item"><a class="ama-link" href="{% url 'ama_detail' ama.id %}">{{ ama.title }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

{% if is_paginated %}
<div class="center-align">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="waves-effect">
      <a href="{% url 'index' %}?page={{ page_obj.previous_page_number }}">Previous</a>
    </li>
    {% endif %}

    {% for i in range %}
    <li>
      <a href="{% url 'index' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="waves-effect">
      <a href="{% url 'index' %}?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% endif %}
  </ul>
</div>
{% endif %}
{% endblock %}

{% block right-content %}
<h5>
  <a href="{% url 'createama' %}" class="btn btn-primary btn-lg">
    SUBMIT AN AMA
  </a>
</h5>
{% endblock %}

home/templates/ama/question.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <div class="col-xs-12">
    <a href="{% url 'ama_detail' ama.id %}">&#8592Back to AMA</a>

    <h1>{{ ama.title }}</h1>

    <div class="">
      <h4>{{ question.question_text|linebreaksbr }}</h4>
    </div>

    <form class="speech-form" action="{{ request.path }}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% if user == ama.author %}
        <label for="response">Answer</label>
        {% else %}
        <label for="response">Comment</label>
        {% endif %}
        <textarea name="response" class="form-control question" rows="1" cols="1"></textarea>

        <input type="submit" value="Save">
      </div>
    </form>
  </div>
</div>
{% endblock %}